server.port=8080

spring.r2dbc.url=r2dbc:postgresql://localhost:5433/telemetry?options=TimeZone=UTC
spring.r2dbc.username=telemetry
spring.r2dbc.password=telemetry

spring.flyway.enabled=true
spring.flyway.url=jdbc:postgresql://localhost:5433/telemetry?options=-c%20TimeZone=UTC
spring.flyway.user=telemetry
spring.flyway.password=telemetry

server.error.include-message=always